//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int customerID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime order_createtime { get; set; }
        public System.DateTime order_closetime { get; set; }
        public int Priority { get; set; }
        public int IsActive { get; set; }
        public int IsBillSent { get; set; }
        public int IsPaid { get; set; }
        public int IsShipped { get; set; }
    }
}
