//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public double MoneySpend { get; set; }
        public double MoneyReceived { get; set; }
        public int OrderID { get; set; }
    }
}
