//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checker
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodPrice
    {
        public int Id { get; set; }
        public string GoodRealName { get; set; }
        public int Retailer { get; set; }
        public double Price { get; set; }
        public string Goodlink { get; set; }
        public string Brand { get; set; }
    }
}
