//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageProvider
    {
        public int Id { get; set; }
        public string ProviderName { get; set; }
        public int IsActive { get; set; }
        public string QueryURL { get; set; }
    }
}
